# Generated by Django 3.0 on 2019-12-04 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=1, max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('bustype', models.CharField(max_length=100)),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('peak', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('off', models.IntegerField(default=0)),
            ],
        ),
    ]
