# Generated by Django 3.0 on 2019-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=300)),
                ('hoteltype', models.IntegerField(default=1)),
                ('hotelname', models.CharField(max_length=100)),
                ('mealplan', models.CharField(max_length=20)),
                ('pax', models.FloatField(default=2)),
                ('peak', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('off', models.IntegerField()),
                ('bitly', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
